- name: create marathon-lb templates dir
  file: path=/etc/marathon-lb/templates state=directory mode=0777

- name: copy templates
  copy: src={{ item }} dest=/etc/marathon-lb/templates
  with_items:
    - HAPROXY_HTTP_FRONTEND_ACL_WITH_PATH

- name: start marathon-lb
  docker_container:
    name: marathon-lb
    image: 0x06065a/marathon-lb:1.3.3
    network_mode: host
    env:
      PORTS: 9090
    privileged: yes
    volumes:
      - /etc/marathon-lb/templates:/marathon-lb/templates
    command: sse --marathon http://{{ ansible_eth1.ipv4.address }}:8080 --group sandbox --health-check
